version: 2

models:
  - name: dim_hesa_disability
    description: "Codes/labels provided by HESA for student to self-report disabilities"
    columns:
      - name: dim_hesa_disability_key
        data_type: varchar(30)
        description: "Surrogate key, structured DIS_<religion_code>_<hesa_delivery> for human readability"

      - name: disability_code
        data_type: varchar(5)
        description: "Code representing disability"

      - name: disability_label
        data_type: varchar(400)
        description: "Disability short description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_ethnicity
    description: "Codes/labels provided by HESA for student to indicate their ethnicity"
    columns:
      - name: dim_hesa_ethnicity_key
        data_type: varchar(30)
        description: "Surrogate key, structured ETH_<religion_code>_<hesa_delivery> for human readability"

      - name: ethnicity_code
        data_type: varchar(5)
        description: "Code representing ethnicity"

      - name: ethnicity_label
        data_type: varchar(400)
        description: "Ethnicity label/description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_genderid
    description: "Codes/labels provided by HESA for student to indicate their gender identity"
    columns:
      - name: dim_hesa_genderid_key
        data_type: varchar(30)
        description: "Surrogate key, structured GID_<religion_code>_<hesa_delivery> for human readability"

      - name: genderid_code
        data_type: varchar(5)
        description: "Code representing a gender identity"

      - name: genderid_label
        data_type: varchar(400)
        description: "Gender identity label/description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_program
    description: ""
    columns:
      - name: dim_hesa_program_key
        data_type: varchar(61)
        description: "Surrogate key, structured PGM_<program_guid>_<hesa_delivery> for human readability"

      - name: program_guid
        data_type: char(36)
        description: "HESA unique identifier for program of study"

      - name: program_code
        data_type: varchar(10)
        description: "Human-readable code representing program of study (typically a degree course)"

      - name: program_name
        data_type: varchar(100)
        description: "HESA description of program of study (typically name of degree)"

      - name: source_file
        data_type: varchar(250)
        description: ""

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

  - name: dim_hesa_religion
    description: "Codes/labels provided by HESA for student to indicate their religion"
    columns:
      - name: dim_hesa_religion_key
        data_type: varchar(30)
        description: "Surrogate key, structured REL_<religion_code>_<hesa_delivery> for human readability"

      - name: religion_code
        data_type: varchar(5)
        description: "Code representing religion"

      - name: religion_label
        data_type: varchar(400)
        description: "Religion name assigned by HESA"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: "CSV filename from which the code definition was loaded"

  - name: dim_hesa_sexid
    description: "Codes/labels provided by HESA for student to indicate their sexual identity"
    columns:
      - name: dim_hesa_sexid_key
        data_type: varchar(30)
        description: "Surrogate key, structured SXI_<sexid_code>_<hesa_delivery> for human readability"

      - name: sexid_code
        data_type: varchar(5)
        description: "Code representing sexual identity"

      - name: sexid_label
        data_type: varchar(400)
        description: "Sexual identity name/description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_sexort
    description: "Codes/labels provided by HESA for student to indicate their sexual orientation"
    columns:
      - name: dim_hesa_sexort_key
        data_type: varchar(30)
        description: "Surrogate key, structured SXO_<sexort_code>_<hesa_delivery> for human readability"

      - name: sexort_code
        data_type: varchar(5)
        description: "Code representing sexual orientation"

      - name: sexort_label
        data_type: varchar(400)
        description: "Sexual orientation name/description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_student
    description: "HESA-provided student records with demographic info"
    columns:
      - name: dim_hesa_student_key
        data_type: varchar(61)
        description: "Surrogate key, structured STU_<student_guid>_<hesa_delivery> for human readability"

      - name: student_guid
        data_type: char(36)
        description: "HESA-provided unique identifier for a student, persisting through all courses of study"

      - name: first_names
        data_type: varchar(250)
        description: ""

      - name: last_name
        data_type: varchar(250)
        description: ""

      - name: phone
        data_type: varchar(250)
        description: ""

      - name: email
        data_type: varchar(250)
        description: ""

      - name: dob
        data_type: date
        description: ""

      - name: home_addr
        data_type: varchar(250)
        description: ""

      - name: home_postcode
        data_type: varchar(50)
        description: ""

      - name: home_country
        data_type: varchar(100)
        description: ""

      - name: term_addr
        data_type: varchar(250)
        description: ""

      - name: term_postcode
        data_type: varchar(50)
        description: ""

      - name: term_country
        data_type: varchar(100)
        description: ""

      - name: source_file
        data_type: varchar(250)
        description: ""

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: ethnicity
        data_type: varchar(3)
        description: ""

      - name: gender
        data_type: varchar(3)
        description: ""

      - name: religion
        data_type: varchar(3)
        description: ""

      - name: sexid
        data_type: varchar(3)
        description: ""

      - name: sexort
        data_type: varchar(3)
        description: ""

      - name: trans
        data_type: varchar(3)
        description: ""

      - name: ethnicity_grp1
        data_type: varchar(3)
        description: ""

      - name: ethnicity_grp2
        data_type: varchar(3)
        description: ""

      - name: ethnicity_grp3
        data_type: varchar(3)
        description: ""

  - name: dim_hesa_trans
    description: "Codes/labels provided by HESA for student to indicate whether their trans status"
    columns:
      - name: dim_hesa_trans_key
        data_type: varchar(30)
        description: "Surrogate key, structured TRA_<sexort_code>_<hesa_delivery> for human readability"

      - name: trans_code
        data_type: varchar(5)
        description: "Code representing transgender status"

      - name: trans_label
        data_type: varchar(400)
        description: "Transgender status description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_z_ethnicgrp1
    description: "HESA-derived ethnicity grouping (level 1 - least detailed grain)"
    columns:
      - name: dim_hesa_z_ethnicgrp1_key
        data_type: varchar(30)
        description: "Surrogate key, structured EG1_<code>_<hesa_delivery> for human readability"

      - name: z_ethnicgrp1_code
        data_type: varchar(5)
        description: "Code representing level 1 ethnicity grouping"

      - name: z_ethnicgrp1_label
        data_type: varchar(400)
        description: "Ethnicity grouping (level 1) description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_z_ethnicgrp2
    description: "HESA-derived ethnicity grouping (level 2 - medium detailed grain)"
    columns:
      - name: dim_hesa_z_ethnicgrp2_key
        data_type: varchar(30)
        description: "Surrogate key, structured EG2_<code>_<hesa_delivery> for human readability"

      - name: z_ethnicgrp2_code
        data_type: varchar(5)
        description: "Code representing level 2 ethnicity grouping"

      - name: z_ethnicgrp2_label
        data_type: varchar(400)
        description: "Ethnicity grouping (level 2) description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""

  - name: dim_hesa_z_ethnicgrp3
    description: "HESA-derived ethnicity grouping (level 3 - most detailed grain)"
    columns:
      - name: dim_hesa_z_ethnicgrp3_key
        data_type: varchar(30)
        description: "Surrogate key, structured EG3_<code>_<hesa_delivery> for human readability"

      - name: z_ethnicgrp3_code
        data_type: varchar(5)
        description: "Code representing level 3 ethnicity grouping"

      - name: z_ethnicgrp3_label
        data_type: varchar(400)
        description: "Ethnicity grouping (level 3) description"

      - name: hesa_delivery
        data_type: varchar(20)
        description: "Identifies the originating fileset from  HESA (collection code + actual delivery date)"

      - name: source_file
        data_type: varchar(250)
        description: ""


