version: 2

sources:
- name: hesa
  database: college_dev
  schema: college_dev
  tables:
    - name: stage_hesa_nn056_lookup_disability
    - name: stage_hesa_nn056_lookup_ethnicity
    - name: stage_hesa_nn056_lookup_genderid
    - name: stage_hesa_nn056_lookup_religion
